### ISSUE TITLE
error in ms_deformable_im2col_cuda: invalid device function

### ISSUE THREAD

**Issue by Lisiyuan555** [woodfrog/heat#1]
Thanks for sharing the code!
But I'm having some problems trying to use this code.You mentioned in readme.txt that the python version used is 3.7, but after I run
```
$ conda create -n try python=3.7
$ conda activate try
$ pip install -r requirements.txt
```
I met an error:

![56b2a26123949a51b1278cde116e78e](https://user-images.githubusercontent.com/68208839/173986292-aada6e77-5ccd-41d0-ae5c-d3008d195afb.png)

So I changed to version 3.8. After this I compiled without problems, but when trying to run:

`$ python infer.py --checkpoint_path ./checkpoints/ckpts_heat_s3d_256/checkpoint.pth  --dataset s3d_floorplan --image_size 256 --viz_base ./results/viz_heat_s3d_256 --save_base ./results/npy_heat_s3d_256 `

I met a new error:

![30727555ca32767279f5fcce08fb9d8](https://user-images.githubusercontent.com/68208839/173986884-5ad6eba5-3d00-4ea7-a2bd-eecc3bdf1a81.png)

This looks like a version mismatch issue.
So I would like to ask about the version of CUDA, cuDNN, pytorch and cudatoolkit in the environment where you run the code, so that it can run successfully, thank you very much!

**Comment by woodfrog** [comment]
Hi,

My python version is 3.7.6, and the pip install works well (just checked it again with a new empty environment). Pytorch is shipped with CUDA and cuDNN, so your own CUDA/cuDNN version should not matter. Did you first compile the Deformable Attention operator properly?

**Comment by Lisiyuan555** [comment]
I have successfully run this :
`sh make.sh`
And the last sentence out of the terminal mentions this library `MultiScaleDeformableAttention=1.0`. So I thought my compilation was done.
Do you mean that I need to download and compile the code in this url? [https://github.com/fundamentalvision/Deformable-DETR](url)

**Comment by woodfrog** [comment]
No, the files in this repo should suffice. After the compilation, can you successfully run the test.py in ```./models/ops```? If not, maybe try ```pip install .``` under the path ```./models/ops```.

**Comment by Lisiyuan555** [comment]
QAQ Sadly, I did use python=3.7 in a brand new environment and got that version  error that I first mentioned.
I just tried it again using python=3.8 to create an environment, after running above
```
pip install -r requirements.txt
cd  models/ops/
sh make.sh
```
![01f067c597ad9cd6995464944553556](https://user-images.githubusercontent.com/68208839/174058180-c19a72e1-47f0-41bd-96bc-165163b4058e.png)

It looks everything is ok, but I can't run `test.py` successfully as you say, 

![8f9f80c83c8668f53fa9f24a38372de](https://user-images.githubusercontent.com/68208839/174057510-91d1fd95-9128-4b71-8ee1-90752a48df00.png)

even after runing `pip install .` under the path` ./models/ops`

![081b6a520f5dd1e4c8b3b56eee4eb70](https://user-images.githubusercontent.com/68208839/174057553-885dba95-c932-460f-85b5-4c779fa56bf5.png)

Then I continue to run `test.py` or `infer.py`, output is as same as before. o(╥﹏╥)oDo you have any other suggestions for solving this problem?

**Comment by woodfrog** [comment]
Can you check the cudatoolkit version of your pytorch? According to [this issue in the deformable-DETR repo](https://github.com/fundamentalvision/Deformable-DETR/issues/13#issuecomment-772294398), it seems that the operator is only compatible with CUDA 9.2, so maybe try the command as that comment suggested: ```conda install pytorch=1.5.1 torchvision=0.6.1 cudatoolkit=9.2 -c pytorch```, and then re-compile the operator.

**Comment by Lisiyuan555** [comment]
Ok I will try it. Because `cudatoolkit=10.2` is also compatible with `pytorch=1.5.1 torchvision=0.6.1,` I am using version 10.2, and I will try version 9.2 again. Thanks♪(･ω･)ﾉ

**Comment by Lisiyuan555** [comment]
www I finally found the problem, because when I compiled and ran `sh make.sh`, I did not delete the `build` folder originally compiled with other versions of cuda, resulting in software conflicts between different versions. In fact, the cudatoolkit version 10.2 I used can also run successfully.
But I don't know the reason why it didn't run successfully at first. Maybe I installed cuda version 10.0 outside conda but installed cudatoolkit version 10.2 in the conda environment? In short, I now use cuda version 10.2 both outside and in conda to run successfully.
By the way, in your readme.txt there is a place where `cd ../..` is mistakenly written as `cd ...`
![23d2b1f0fce918a99b8b4331c4b7d78](https://user-images.githubusercontent.com/68208839/174221094-0a78c7b5-f285-4e97-bc8b-c57391250cfc.png)
At last, thank you so much for helping me!

**Comment by woodfrog** [comment]
> www I finally found where the problem is, because I did not delete the original `build` folder after you compiled it when I ran `sh make.sh`, which caused conflicts between different versions of the software. In fact, the 10.2 version cudatoolkit I used can also run successfully. Some suggestions:
> 
> 1. You can delete your compiled build folder in the github code to avoid other people encountering this kind of problem.
> 2. In your readme.txt there is a place where `cd ../..` is mistakenly written as `cd ...`
>    ![23d2b1f0fce918a99b8b4331c4b7d78](https://user-images.githubusercontent.com/68208839/174221094-0a78c7b5-f285-4e97-bc8b-c57391250cfc.png)
>    At last, thank you so much for helping me!

Thanks for the feedback, and glad it finally works for you. But it seems that there is no build folder in the repo, I wonder where did you get it. Could you provide a link to that path?

**Comment by Lisiyuan555** [comment]
Ohoooooo sorry then! Looks like it's all my own problem then.
Next time I will definitely remember to delete the `Build` folder after the recompile.o(╥﹏╥)o

**Comment by eslambakr** [comment]
Hi @Lisiyuan555 ,
I am facing the same issue, can u let me know your pytorch version as I am trying to use 1.12 with cuda10.2 but it does not work for me.
Thanks in advance!
