### ISSUE TITLE
about 'extract_regions'

### ISSUE THREAD

**Issue by zjhthu** [woodfrog/heat#6]
Hi, I find there is a postprocessing after getting the planar graph, which extracts room from the edges. But I can not find a detailed illustration of this part in the paper. Can you give an explanation of how it works?

**Comment by woodfrog** [comment]
Hi, thank you for your interest, and it's a good catch. That postprocessing algorithm for extracting regions from a planar graph is based on these two papers: ["An optimal algorithm for extracting the regions of a plane graph"](https://www.sciencedirect.com/science/article/abs/pii/016786559390104L) and ["Surface extraction from line drawings of a polyhedron"](https://www.sciencedirect.com/science/article/abs/pii/016786559190017G). The algorithm described in Section.3 of the first paper suffices for our tasks. This is not part of our method but is necessary to run the room-based evaluation pipeline (borrowed from [MonteFloor](https://arxiv.org/abs/2103.11161)), and we should have included these details in the paper.

**Comment by zjhthu** [comment]
thanks!
